vich_uploader:
    db_driver: orm

    mappings:
        actu_image:
            uri_prefix: /img/actus
            upload_destination: '%kernel.project_dir%/public/img/actus'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        etablissement_image:
            uri_prefix: /img/etablissement
            upload_destination: '%kernel.project_dir%/public/img/etablissement'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

