vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        actu_image:
            uri_prefix: /img/actus
            upload_destination: '%kernel.project_dir%/public/img/actus'
            
